# GitHub Repository Site
repository: KFuller21/kfuller21.github.io

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: images/favicon.ico

# Content configuration version
version: 1.0.0

# Personal Info
name: Kristen Fuller
title: Cloud Engineer
email: kristen.leigh.fuller@gmail.com
website: https://www.kristenlfuller.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: kfuller21
linkedin_username: kristenlfuller
# Additional icon links
additional_links:
- title: Resume Portfolio
  icon: fas fa-globe
  url: https://www.kristenlfuller.com

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# ga_tracking: UA-2709176-10
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# Define color scheme; dark/light/default
color_scheme: dark

# About Section
about_title: About Me
about_profile_image: images/avatar.jpg
about_content: |
  Hi, I'm Kristen, a dedicated Cloud Engineer with a passion for automation and a knack for optimizing cloud operations.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Wings</mark>

  Life's too short to manually deploy clouds. Let's automate and <mark>'git'</mark> to the good stuff!

  <mark>My main skills include:</mark>
  Cloud Technologies (AWS GovCloud) | DevOps Methodologies | Automation Scalability and High-Performance Solutions
  Linux | HTML/SCSS/Jekyll | PowerShell | Bash | CI/CD | Configuration Management (GitHub) | IaC Tools (Terraform/CloudFormation)
  Security & Compliance | Monitoring and Reporting | Software Development Life Cycle | <mark>The Best Teammate</mark>

# Website Content
content:
  - title: Experience 
    layout: list
    content:
      - layout: left
        title: GovCIO
        link: govcio.com
        sub_title: Production Cloud Engineer
        caption: May 2023 - Present
        description: |
          In my role as a Cloud Production Engineer, I've been at the forefront of driving innovation in cloud operations.
          
          I've collaborated with cross-functional teams, fostering DevOps methodologies and enhancing communication and integration throughout the application lifecycle. 
          
          Supporting AWS GovCloud environments, I've enabled efficient configuration and integrations for the Appian SaaS platform, all while ensuring the continuous availability, durability, and scalability of cloud operations.
  
  - title: Education 
    layout: list
    content:
      - layout: left
        title: Western Governors University
        caption: 2022
        sub_title: BS Cloud Computing - AWS Track

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in Cloud and DevOps engineering some of my other interests and hobbies are:
      - Soccer
      - Wine Tasting
      - Hanging out with my Family
      - Trying new restaurants 

  #    Look at this cool image  
  #    ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
     # - layout: top-middle
      #  title: 
      #  link: 
        # link_text: Project Website
      #  additional_links:
        #  - title:  
        #    icon: 
        #    url: 
      #  quote: >
      #    This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs


# Footer contents [footer_custom.html]
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%m/%d/%y" # Uses ruby's time format

# Build settings
remote_theme: KFuller21/kfuller21.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-last-modified-at
 - jekyll-github-metadata
 - jekyll-include-cache
